kind: pipeline
type: docker
name: default

steps:
- name: compiler-setup
  image: alpine
  commands:
  - apk update
  - apk add git cmake make ninja clang build-base # build-base includes all possible headers and runtimes
- name: compile
  image: alpine
  commands:
  - make