kind: pipeline
type: docker
name: default


steps:
- name: compile
  image: alpine
  commands:
  - apk update
  - apk add git cmake make ninja clang build-base # build-base includes all possible headers and runtimes for both c and c++
  - make
