#include "function.hpp"
#include "logc/log.h"

namespace Script {

std::unordered_map<std::string, FunctionInfo> FunctionResolver::functions({
    { "unusedfunction0", { 0x1000, "UnusedFunction0", "", "" } },
    { "getdistance", { 0x1001, "GetDistance", "", "" } },
    { "additem", { 0x1002, "AddItem", "", "" } },
    { "setessential", { 0x1003, "SetEssential", "", "" } },
    { "rotate", { 0x1004, "Rotate", "", "" } },
    { "getlocked", { 0x1005, "GetLocked", "", "" } },
    { "getpos", { 0x1006, "GetPos", "", "" } },
    { "setpos", { 0x1007, "SetPos", "", "" } },
    { "getangle", { 0x1008, "GetAngle", "", "" } },
    { "setangle", { 0x1009, "SetAngle", "", "" } },
    { "getstartingpos", { 0x100A, "GetStartingPos", "", "" } },
    { "getstartingangle", { 0x100B, "GetStartingAngle", "", "" } },
    { "getsecondspassed", { 0x100C, "GetSecondsPassed", "", "" } },
    { "activate", { 0x100D, "Activate", "", "" } },
    { "getactorvalue", { 0x100E, "GetActorValue", "GetAV", "Get an actor value. [player.getav luck]" } },
    { "setactorvalue", { 0x100F, "SetActorValue", "SetAV", "Set an actor value. [player.setav luck, 75]" } },
    { "modactorvalue", { 0x1010, "ModActorValue", "ModAV", "Modify an actor value. [player.modav luck, -10]" } },
    { "setatstart", { 0x1011, "SetAtStart", "", "" } },
    { "getcurrenttime", { 0x1012, "GetCurrentTime", "", "" } },
    { "playgroup", { 0x1013, "PlayGroup", "", "IE: PlayGroup SEQNAME 1" } },
    { "loopgroup", { 0x1014, "LoopGroup", "", "" } },
    { "skipanim", { 0x1015, "SkipAnim", "", "" } },
    { "startcombat", { 0x1016, "StartCombat", "", "" } },
    { "stopcombat", { 0x1017, "StopCombat", "", "" } },
    { "getscale", { 0x1018, "GetScale", "", "" } },
    { "ismoving", { 0x1019, "IsMoving", "", "Is the actor moving?" } },
    { "isturning", { 0x101A, "IsTurning", "", "Is the actor turning?" } },
    { "getlineofsight", { 0x101B, "GetLineOfSight", "GetLOS", "" } },
    { "addspell", { 0x101C, "AddSpell", "", "" } },
    { "removespell", { 0x101D, "RemoveSpell", "", "" } },
    { "cast", { 0x101E, "Cast", "", "" } },
    { "getbuttonpressed", { 0x101F, "GetButtonPressed", "", "" } },
    { "getinsamecell", { 0x1020, "GetInSameCell", "", "" } },
    { "enable", { 0x1021, "Enable", "", "" } },
    { "disable", { 0x1022, "Disable", "", "" } },
    { "getdisabled", { 0x1023, "GetDisabled", "", "" } },
    { "menumode", { 0x1024, "MenuMode", "", "" } },
    { "placeatme", { 0x1025, "PlaceAtMe", "", "" } },
    { "playsound", { 0x1026, "PlaySound", "", "Play a 2D sound. (Optional: 1 to indicate a system sound, 0 otherwise." } },
    { "getdisease", { 0x1027, "GetDisease", "", "" } },
    { "getvampire", { 0x1028, "GetVampire", "", "" } },
    { "getclothingvalue", { 0x1029, "GetClothingValue", "", "" } },
    { "samefaction", { 0x102A, "SameFaction", "", "" } },
    { "samerace", { 0x102B, "SameRace", "", "" } },
    { "samesex", { 0x102C, "SameSex", "", "" } },
    { "getdetected", { 0x102D, "GetDetected", "", "" } },
    { "getdead", { 0x102E, "GetDead", "", "" } },
    { "getitemcount", { 0x102F, "GetItemCount", "", "" } },
    { "getgold", { 0x1030, "GetGold", "", "" } },
    { "getsleeping", { 0x1031, "GetSleeping", "", "" } },
    { "gettalkedtopc", { 0x1032, "GetTalkedToPC", "", "" } },
    { "say", { 0x1033, "Say", "", "" } },
    { "sayto", { 0x1034, "SayTo", "", "" } },
    { "getscriptvariable", { 0x1035, "GetScriptVariable", "", "" } },
    { "startquest", { 0x1036, "StartQuest", "", "" } },
    { "stopquest", { 0x1037, "StopQuest", "", "" } },
    { "getquestrunning", { 0x1038, "GetQuestRunning", "GetQR", "" } },
    { "setstage", { 0x1039, "SetStage", "", "" } },
    { "getstage", { 0x103A, "GetStage", "", "" } },
    { "getstagedone", { 0x103B, "GetStageDone", "", "" } },
    { "getfactionrankdifference", { 0x103C, "GetFactionRankDifference", "", "" } },
    { "getalarmed", { 0x103D, "GetAlarmed", "", "" } },
    { "israining", { 0x103E, "IsRaining", "", "" } },
    { "getattacked", { 0x103F, "GetAttacked", "", "" } },
    { "getiscreature", { 0x1040, "GetIsCreature", "", "" } },
    { "getlocklevel", { 0x1041, "GetLockLevel", "", "" } },
    { "getshouldattack", { 0x1042, "GetShouldAttack", "", "" } },
    { "getincell", { 0x1043, "GetInCell", "", "" } },
    { "getisclass", { 0x1044, "GetIsClass", "", "" } },
    { "getisrace", { 0x1045, "GetIsRace", "", "" } },
    { "getissex", { 0x1046, "GetIsSex", "", "" } },
    { "getinfaction", { 0x1047, "GetInFaction", "", "" } },
    { "getisid", { 0x1048, "GetIsID", "", "" } },
    { "getfactionrank", { 0x1049, "GetFactionRank", "", "" } },
    { "getglobalvalue", { 0x104A, "GetGlobalValue", "", "" } },
    { "issnowing", { 0x104B, "IsSnowing", "", "" } },
    { "getdisposition", { 0x104C, "GetDisposition", "", "" } },
    { "getrandompercent", { 0x104D, "GetRandomPercent", "", "" } },
    { "streammusic", { 0x104E, "StreamMusic", "", "" } },
    { "getquestvariable", { 0x104F, "GetQuestVariable", "", "" } },
    { "getlevel", { 0x1050, "GetLevel", "", "" } },
    { "getarmorrating", { 0x1051, "GetArmorRating", "", "" } },
    { "removeitem", { 0x1052, "RemoveItem", "", "" } },
    { "moddisposition", { 0x1053, "ModDisposition", "", "" } },
    { "getdeadcount", { 0x1054, "GetDeadCount", "", "" } },
    { "showmap", { 0x1055, "ShowMap", "", "" } },
    { "startconversation", { 0x1056, "StartConversation", "", "Start a conversation [Bob.StartConversation Joe, SecretTopic]" } },
    { "drop", { 0x1057, "Drop", "", "" } },
    { "addtopic", { 0x1058, "AddTopic", "", "" } },
    { "showmessage", { 0x1059, "ShowMessage", "", "" } },
    { "setalert", { 0x105A, "SetAlert", "", "" } },
    { "getisalerted", { 0x105B, "GetIsAlerted", "", "" } },
    { "look", { 0x105C, "Look", "", "" } },
    { "stoplook", { 0x105D, "StopLook", "", "" } },
    { "evaluatepackage", { 0x105E, "EvaluatePackage", "evp", "" } },
    { "sendassaultalarm", { 0x105F, "SendAssaultAlarm", "", "" } },
    { "enableplayercontrols", { 0x1060, "EnablePlayerControls", "", "7 optional (0/1) values. movement\\pipboy\\fighting\\pov\\looking\\rollover\\sneaking ex: 1 0 0 1 0 0 0" } },
    { "disableplayercontrols", { 0x1061, "DisablePlayerControls", "", "7 optional (0/1) values. movement\\pipboy\\fighting\\pov\\looking\\rollover\\sneaking ex: 1 0 0 1 0 0 0" } },
    { "getplayercontrolsdisabled", { 0x1062, "GetPlayerControlsDisabled", "", "7optional (0/1) values.movement\\pipboy\\fighting\\pov\\looking\\rollover\\sneaking ex: 1 0 0 1 0 0 0" } },
    { "getheadingangle", { 0x1063, "GetHeadingAngle", "", "" } },
    { "pickidle", { 0x1064, "PickIdle", "", "" } },
    { "isweaponout", { 0x1065, "IsWeaponOut", "", "" } },
    { "istorchout", { 0x1066, "IsTorchOut", "", "" } },
    { "isshieldout", { 0x1067, "IsShieldOut", "", "" } },
    { "createdetectionevent", { 0x1068, "CreateDetectionEvent", "", "" } },
    { "isactionref", { 0x1069, "IsActionRef", "", "" } },
    { "isfacingup", { 0x106A, "IsFacingUp", "", "" } },
    { "getknockedstate", { 0x106B, "GetKnockedState", "", "" } },
    { "getweaponanimtype", { 0x106C, "GetWeaponAnimType", "", "" } },
    { "isweaponskilltype", { 0x106D, "IsWeaponSkillType", "", "" } },
    { "getcurrentaipackage", { 0x106E, "GetCurrentAIPackage", "", "" } },
    { "iswaiting", { 0x106F, "IsWaiting", "", "" } },
    { "isidleplaying", { 0x1070, "IsIdlePlaying", "", "" } },
    { "completequest", { 0x1071, "CompleteQuest", "", "" } },
    { "lock", { 0x1072, "Lock", "", "" } },
    { "unlock", { 0x1073, "UnLock", "", "" } },
    { "getminorcrimecount", { 0x1074, "GetMinorCrimeCount", "", "" } },
    { "getmajorcrimecount", { 0x1075, "GetMajorCrimeCount", "", "" } },
    { "getactoraggroradiusviolated", { 0x1076, "GetActorAggroRadiusViolated", "", "" } },
    { "getcrimeknown", { 0x1077, "GetCrimeKnown", "", "" } },
    { "setenemy", { 0x1078, "SetEnemy", "", "" } },
    { "setally", { 0x1079, "SetAlly", "", "" } },
    { "getcrime", { 0x107A, "GetCrime", "", "" } },
    { "isgreetingplayer", { 0x107B, "IsGreetingPlayer", "", "" } },
    { "startmistersandman", { 0x107C, "StartMisterSandMan", "", "" } },
    { "isguard", { 0x107D, "IsGuard", "", "" } },
    { "startcannibal", { 0x107E, "StartCannibal", "", "" } },
    { "hasbeeneaten", { 0x107F, "HasBeenEaten", "", "" } },
    { "getfatiguepercentage", { 0x1080, "GetFatiguePercentage", "GetFatigue", "" } },
    { "getpcisclass", { 0x1081, "GetPCIsClass", "", "" } },
    { "getpcisrace", { 0x1082, "GetPCIsRace", "", "" } },
    { "getpcissex", { 0x1083, "GetPCIsSex", "", "" } },
    { "getpcinfaction", { 0x1084, "GetPCInFaction", "", "" } },
    { "samefactionaspc", { 0x1085, "SameFactionAsPC", "", "" } },
    { "sameraceaspc", { 0x1086, "SameRaceAsPC", "", "" } },
    { "samesexaspc", { 0x1087, "SameSexAsPC", "", "" } },
    { "getisreference", { 0x1088, "GetIsReference", "", "" } },
    { "setfactionrank", { 0x1089, "SetFactionRank", "", "" } },
    { "modfactionrank", { 0x108A, "ModFactionRank", "", "" } },
    { "killactor", { 0x108B, "KillActor", "kill", "" } },
    { "resurrectactor", { 0x108C, "ResurrectActor", "resurrect", "" } },
    { "istalking", { 0x108D, "IsTalking", "", "" } },
    { "getwalkspeed", { 0x108E, "GetWalkSpeed", "GetWalk", "" } },
    { "getcurrentaiprocedure", { 0x108F, "GetCurrentAIProcedure", "", "" } },
    { "gettrespasswarninglevel", { 0x1090, "GetTrespassWarningLevel", "", "" } },
    { "istrespassing", { 0x1091, "IsTrespassing", "", "" } },
    { "isinmyownedcell", { 0x1092, "IsInMyOwnedCell", "", "" } },
    { "getwindspeed", { 0x1093, "GetWindSpeed", "", "" } },
    { "getcurrentweatherpercent", { 0x1094, "GetCurrentWeatherPercent", "getweatherpct", "" } },
    { "getiscurrentweather", { 0x1095, "GetIsCurrentWeather", "getweather", "" } },
    { "iscontinuingpackagepcnear", { 0x1096, "IsContinuingPackagePCNear", "", "" } },
    { "addscriptpackage", { 0x1097, "AddScriptPackage", "", "" } },
    { "removescriptpackage", { 0x1098, "RemoveScriptPackage", "", "" } },
    { "canhaveflames", { 0x1099, "CanHaveFlames", "", "" } },
    { "hasflames", { 0x109A, "HasFlames", "", "" } },
    { "addflames", { 0x109B, "AddFlames", "", "" } },
    { "removeflames", { 0x109C, "RemoveFlames", "", "" } },
    { "getopenstate", { 0x109D, "GetOpenState", "", "" } },
    { "movetomarker", { 0x109E, "MoveToMarker", "MoveTo", "" } },
    { "getsitting", { 0x109F, "GetSitting", "", "" } },
    { "getfurnituremarkerid", { 0x10A0, "GetFurnitureMarkerID", "", "" } },
    { "getiscurrentpackage", { 0x10A1, "GetIsCurrentPackage", "", "" } },
    { "iscurrentfurnitureref", { 0x10A2, "IsCurrentFurnitureRef", "", "" } },
    { "iscurrentfurnitureobj", { 0x10A3, "IsCurrentFurnitureObj", "", "" } },
    { "setsize", { 0x10A4, "SetSize", "CSize", "Shrink/Grow an actor. [player.shrink 0.0 or radius]" } },
    { "removeme", { 0x10A5, "RemoveMe", "", "" } },
    { "dropme", { 0x10A6, "DropMe", "", "" } },
    { "getfactionreaction", { 0x10A7, "GetFactionReaction", "", "" } },
    { "setfactionreaction", { 0x10A8, "SetFactionReaction", "", "" } },
    { "modfactionreaction", { 0x10A9, "ModFactionReaction", "", "" } },
    { "getdayofweek", { 0x10AA, "GetDayOfWeek", "", "" } },
    { "ignorecrime", { 0x10AB, "IgnoreCrime", "", "" } },
    { "gettalkedtopcparam", { 0x10AC, "GetTalkedToPCParam", "", "" } },
    { "removeallitems", { 0x10AD, "RemoveAllItems", "", "" } },
    { "wakeuppc", { 0x10AE, "WakeUpPC", "", "" } },
    { "ispcsleeping", { 0x10AF, "IsPCSleeping", "", "" } },
    { "ispcamurderer", { 0x10B0, "IsPCAMurderer", "", "" } },
    { "setcombatstyle", { 0x10B1, "SetCombatStyle", "setcs", "" } },
    { "playsound3d", { 0x10B2, "PlaySound3D", "", "" } },
    { "selectplayerspell", { 0x10B3, "SelectPlayerSpell", "spspell", "" } },
    { "getdetectionlevel", { 0x10B4, "GetDetectionLevel", "", "" } },
    { "isactordetected", { 0x10B5, "IsActorDetected", "", "" } },
    { "getequipped", { 0x10B6, "GetEquipped", "", "" } },
    { "wait", { 0x10B7, "Wait", "", "" } },
    { "stopwaiting", { 0x10B8, "StopWaiting", "", "" } },
    { "isswimming", { 0x10B9, "IsSwimming", "", "" } },
    { "scripteffectelapsedseconds", { 0x10BA, "ScriptEffectElapsedSeconds", "", "" } },
    { "setcellpublicflag", { 0x10BB, "SetCellPublicFlag", "setpublic", "Set public flag on cell. [setpublic MyCell 1]" } },
    { "getpcsleephours", { 0x10BC, "GetPCSleepHours", "", "" } },
    { "setpcsleephours", { 0x10BD, "SetPCSleepHours", "", "" } },
    { "getamountsoldstolen", { 0x10BE, "GetAmountSoldStolen", "", "" } },
    { "modamountsoldstolen", { 0x10BF, "ModAmountSoldStolen", "", "" } },
    { "getignorecrime", { 0x10C0, "GetIgnoreCrime", "", "" } },
    { "getpcexpelled", { 0x10C1, "GetPCExpelled", "", "" } },
    { "setpcexpelled", { 0x10C2, "SetPCExpelled", "", "" } },
    { "getpcfactionmurder", { 0x10C3, "GetPCFactionMurder", "", "" } },
    { "setpcfactionmurder", { 0x10C4, "SetPCFactionMurder", "", "" } },
    { "getpcenemyoffaction", { 0x10C5, "GetPCEnemyofFaction", "", "" } },
    { "setpcenemyoffaction", { 0x10C6, "SetPCEnemyofFaction", "", "" } },
    { "getpcfactionattack", { 0x10C7, "GetPCFactionAttack", "", "" } },
    { "setpcfactionattack", { 0x10C8, "SetPCFactionAttack", "", "" } },
    { "unusedfunction21", { 0x10C9, "UnusedFunction21", "", "" } },
    { "unusedfunction22", { 0x10CA, "UnusedFunction22", "", "" } },
    { "getdestroyed", { 0x10CB, "GetDestroyed", "", "" } },
    { "setdestroyed", { 0x10CC, "SetDestroyed", "", "" } },
    { "getactionref", { 0x10CD, "GetActionRef", "getAR", "" } },
    { "getself", { 0x10CE, "GetSelf", "this", "" } },
    { "getcontainer", { 0x10CF, "GetContainer", "", "" } },
    { "getforcerun", { 0x10D0, "GetForceRun", "", "" } },
    { "setforcerun", { 0x10D1, "SetForceRun", "", "" } },
    { "getforcesneak", { 0x10D2, "GetForceSneak", "", "" } },
    { "setforcesneak", { 0x10D3, "SetForceSneak", "", "" } },
    { "advancepcskill", { 0x10D4, "AdvancePCSkill", "AdvSkill", "" } },
    { "advancepclevel", { 0x10D5, "AdvancePCLevel", "AdvLevel", "" } },
    { "hasmagiceffect", { 0x10D6, "HasMagicEffect", "", "" } },
    { "getdefaultopen", { 0x10D7, "GetDefaultOpen", "", "Returns 1 if this object is open by default." } },
    { "setdefaultopen", { 0x10D8, "SetDefaultOpen", "", "A value of 1 will make the object open by default." } },
    { "showclassmenu", { 0x10D9, "ShowClassMenu", "", "" } },
    { "showracemenu", { 0x10DA, "ShowRaceMenu", "", "" } },
    { "getanimaction", { 0x10DB, "GetAnimAction", "", "Return the actors current anim action." } },
    { "shownamemenu", { 0x10DC, "ShowNameMenu", "", "" } },
    { "setopenstate", { 0x10DD, "SetOpenState", "", "A value of 1 will make the object open." } },
    { "unusedfunction26", { 0x10DE, "UnusedFunction26", "", "" } },
    { "isspelltarget", { 0x10DF, "IsSpellTarget", "", "" } },
    { "getvatsmode", { 0x10E0, "GetVATSMode", "", "" } },
    { "getpersuasionnumber", { 0x10E1, "GetPersuasionNumber", "", "" } },
    { "getsandman", { 0x10E2, "GetSandman", "", "" } },
    { "getcannibal", { 0x10E3, "GetCannibal", "", "" } },
    { "getisclassdefault", { 0x10E4, "GetIsClassDefault", "", "" } },
    { "getclassdefaultmatch", { 0x10E5, "GetClassDefaultMatch", "", "" } },
    { "getincellparam", { 0x10E6, "GetInCellParam", "", "" } },
    { "setinchargen", { 0x10E7, "SetInChargen", "", "A value of 1 will be in chargen." } },
    { "getcombattarget", { 0x10E8, "GetCombatTarget", "", "" } },
    { "getpackagetarget", { 0x10E9, "GetPackageTarget", "", "" } },
    { "showspellmaking", { 0x10EA, "ShowSpellMaking", "", "" } },
    { "getvatstargetheight", { 0x10EB, "GetVatsTargetHeight", "", "" } },
    { "setghost", { 0x10EC, "SetGhost", "", "A value of 1 will make the NPC act as a 'ghost'." } },
    { "getisghost", { 0x10ED, "GetIsGhost", "", "Returns 1 if the actor is acting as a 'ghost'." } },
    { "equipitem", { 0x10EE, "EquipItem", "EquipObject", "" } },
    { "unequipitem", { 0x10EF, "UnequipItem", "UnEquipObject", "" } },
    { "setclass", { 0x10F0, "SetClass", "", "" } },
    { "setunconscious", { 0x10F1, "SetUnconscious", "", "A value of 1 will be unconscious." } },
    { "getunconscious", { 0x10F2, "GetUnconscious", "", "Returns 1 if is unconscious." } },
    { "setrestrained", { 0x10F3, "SetRestrained", "", "A value of 1 will be restrained." } },
    { "getrestrained", { 0x10F4, "GetRestrained", "", "Returns 1 if is restrained." } },
    { "forceflee", { 0x10F5, "ForceFlee", "Flee", "Forces a actor to flee if destination or cell is passed in uses them" } },
    { "getisuseditem", { 0x10F6, "GetIsUsedItem", "", "" } },
    { "getisuseditemtype", { 0x10F7, "GetIsUsedItemType", "", "" } },
    { "unusedfunction9", { 0x10F8, "UnusedFunction9", "", "" } },
    { "unusedfunction10", { 0x10F9, "UnusedFunction10", "", "" } },
    { "unusedfunction11", { 0x10FA, "UnusedFunction11", "", "" } },
    { "unusedfunction12", { 0x10FB, "UnusedFunction12", "", "" } },
    { "unusedfunction13", { 0x10FC, "UnusedFunction13", "", "" } },
    { "unusedfunction14", { 0x10FD, "UnusedFunction14", "", "" } },
    { "getisplayablerace", { 0x10FE, "GetIsPlayableRace", "", "" } },
    { "getoffersservicesnow", { 0x10FF, "GetOffersServicesNow", "", "" } },
    { "getgamesetting", { 0x1100, "GetGameSetting", "GetGS", "" } },
    { "stopcombatalarmonactor", { 0x1101, "StopCombatAlarmOnActor", "SCAOnActor", "" } },
    { "getuseditemlevel", { 0x1102, "GetUsedItemLevel", "", "" } },
    { "getuseditemactivate", { 0x1103, "GetUsedItemActivate", "", "" } },
    { "setweather", { 0x1104, "SetWeather", "sw", "Sets the active weather to the specified type" } },
    { "forcetakecover", { 0x1105, "ForceTakeCover", "TakeCover", "Forces a actor to move away from the target actor for a period of time" } },
    { "modbartergold", { 0x1106, "ModBarterGold", "", "" } },
    { "setbartergold", { 0x1107, "SetBarterGold", "", "" } },
    { "getbartergold", { 0x1108, "GetBarterGold", "", "" } },
    { "istimepassing", { 0x1109, "IsTimePassing", "", "" } },
    { "ispleasant", { 0x110A, "IsPleasant", "", "" } },
    { "iscloudy", { 0x110B, "IsCloudy", "", "" } },
    { "trapupdate", { 0x110C, "TrapUpdate", "", "" } },
    { "setquestobject", { 0x110D, "SetQuestObject", "", "" } },
    { "forceactorvalue", { 0x110E, "ForceActorValue", "ForceAV", "Does modav XXX (value - getav XXX). [player.forceav luck 25]" } },
    { "modpcskill", { 0x110F, "ModPCSkill", "ModPCS", "Modify the Players Skill. [modpcs Blunt, 10]" } },
    { "modpcattribute", { 0x1110, "ModPCAttribute", "ModPCA", "Modify an actor value. [modpca luck, 10]" } },
    { "enablefasttravel", { 0x1111, "EnableFastTravel", "EnableFast", "" } },
    { "getarmorratingupperbody", { 0x1112, "GetArmorRatingUpperBody", "", "" } },
    { "getparentref", { 0x1113, "GetParentRef", "", "" } },
    { "playbink", { 0x1114, "PlayBink", "", "" } },
    { "getbaseactorvalue", { 0x1115, "GetBaseActorValue", "GetBaseAV", "Get a base actor value. [player.getbaseav luck]" } },
    { "isowner", { 0x1116, "IsOwner", "", "get the ownership of the ref" } },
    { "setownership", { 0x1117, "SetOwnership", "", "" } },
    { "iscellowner", { 0x1118, "IsCellOwner", "", "get the ownership of the ref" } },
    { "setcellownership", { 0x1119, "SetCellOwnership", "", "" } },
    { "ishorsestolen", { 0x111A, "IsHorseStolen", "", "" } },
    { "setcellfullname", { 0x111B, "SetCellFullName", "", "" } },
    { "setactorfullname", { 0x111C, "SetActorFullName", "", "" } },
    { "isleftup", { 0x111D, "IsLeftUp", "", "" } },
    { "issneaking", { 0x111E, "IsSneaking", "", "" } },
    { "isrunning", { 0x111F, "IsRunning", "", "" } },
    { "getfriendhit", { 0x1120, "GetFriendHit", "", "" } },
    { "isincombat", { 0x1121, "IsInCombat", "", "" } },
    { "setpackduration", { 0x1122, "SetPackDuration", "SPDur", "" } },
    { "playmagicshadervisuals", { 0x1123, "PlayMagicShaderVisuals", "PMS", "" } },
    { "playmagiceffectvisuals", { 0x1124, "PlayMagicEffectVisuals", "PME", "" } },
    { "stopmagicshadervisuals", { 0x1125, "StopMagicShaderVisuals", "SMS", "" } },
    { "stopmagiceffectvisuals", { 0x1126, "StopMagicEffectVisuals", "SME", "" } },
    { "resetinterior", { 0x1127, "ResetInterior", "", "" } },
    { "isanimplaying", { 0x1128, "IsAnimPlaying", "", "" } },
    { "setactoralpha", { 0x1129, "SetActorAlpha", "SAA", "" } },
    { "enablelinkedpathpoints", { 0x112A, "EnableLinkedPathPoints", "", "" } },
    { "disablelinkedpathpoints", { 0x112B, "DisableLinkedPathPoints", "", "" } },
    { "isininterior", { 0x112C, "IsInInterior", "", "" } },
    { "forceweather", { 0x112D, "ForceWeather", "fw", "Forces the active weather to the specified type, without transition." } },
    { "toggleactorsai", { 0x112E, "ToggleActorsAI", "", "" } },
    { "isactorsaioff", { 0x112F, "IsActorsAIOff", "", "" } },
    { "iswaterobject", { 0x1130, "IsWaterObject", "", "Water condition used for drinking animation." } },
    { "unusedfunction15", { 0x1131, "UnusedFunction15", "", "" } },
    { "isactorusingatorch", { 0x1132, "IsActorUsingATorch", "", "" } },
    { "setlevel", { 0x1133, "SetLevel", "", "" } },
    { "resetfalldamagetimer", { 0x1134, "ResetFallDamageTimer", "", "" } },
    { "isxbox", { 0x1135, "IsXBox", "", "" } },
    { "getinworldspace", { 0x1136, "GetInWorldspace", "", "" } },
    { "modpcmiscstat", { 0x1137, "ModPCMiscStat", "ModPCMS", "" } },
    { "getpcmiscstat", { 0x1138, "GetPCMiscStat", "GetPCMS", "" } },
    { "isactorevil", { 0x1139, "IsActorEvil", "", "" } },
    { "isactoravictim", { 0x113A, "IsActorAVictim", "", "" } },
    { "gettotalpersuasionnumber", { 0x113B, "GetTotalPersuasionNumber", "", "" } },
    { "setscale", { 0x113C, "SetScale", "", "Set the scale of an object" } },
    { "modscale", { 0x113D, "ModScale", "", "Modify the scale of an object" } },
    { "getidledoneonce", { 0x113E, "GetIdleDoneOnce", "", "" } },
    { "killallactors", { 0x113F, "KillAllActors", "killall", "" } },
    { "getnorumors", { 0x1140, "GetNoRumors", "", "" } },
    { "setnorumors", { 0x1141, "SetNoRumors", "", "" } },
    { "dispel", { 0x1142, "Dispel", "", "" } },
    { "whichservicemenu", { 0x1143, "WhichServiceMenu", "", "" } },
    { "triggerhitshader", { 0x1144, "TriggerHitShader", "ths", "" } },
    { "functionunused16", { 0x1145, "FunctionUnused16", "", "" } },
    { "reset3dstate", { 0x1146, "Reset3DState", "", "" } },
    { "isridinghorse", { 0x1147, "IsRidingHorse", "", "" } },
    { "dispelallspells", { 0x1148, "DispelAllSpells", "", "" } },
    { "unusedfunction17", { 0x1149, "UnusedFunction17", "", "" } },
    { "addachievement", { 0x114A, "AddAchievement", "", "" } },
    { "duplicateallitems", { 0x114B, "DuplicateAllItems", "", "" } },
    { "isindangerouswater", { 0x114C, "IsInDangerousWater", "", "" } },
    { "essentialdeathreload", { 0x114D, "EssentialDeathReload", "", "" } },
    { "setshowquestitems", { 0x114E, "SetShowQuestItems", "", "" } },
    { "duplicatenpcstats", { 0x114F, "DuplicateNPCStats", "", "" } },
    { "resethealth", { 0x1150, "ResetHealth", "", "" } },
    { "setignorefriendlyhits", { 0x1151, "SetIgnoreFriendlyHits", "sifh", "Set whether an actor should ignore friendly hits (0-no, 1-yes)" } },
    { "getignorefriendlyhits", { 0x1152, "GetIgnoreFriendlyHits", "gifh", "See if an actor is ignoring friendly hits" } },
    { "isplayerslastriddenhorse", { 0x1153, "IsPlayersLastRiddenHorse", "", "" } },
    { "setactorrefraction", { 0x1154, "SetActorRefraction", "sar", "" } },
    { "setitemvalue", { 0x1155, "SetItemValue", "", "" } },
    { "setrigidbodymass", { 0x1156, "SetRigidBodyMass", "", "" } },
    { "showviewerstrings", { 0x1157, "ShowViewerStrings", "svs", "" } },
    { "releaseweatheroverride", { 0x1158, "ReleaseWeatherOverride", "rwo", "" } },
    { "setallreachable", { 0x1159, "SetAllReachable", "", "" } },
    { "setallvisible", { 0x115A, "SetAllVisible", "", "" } },
    { "setnoavoidance", { 0x115B, "SetNoAvoidance", "", "" } },
    { "sendtrespassalarm", { 0x115C, "SendTrespassAlarm", "", "" } },
    { "setsceneiscomplex", { 0x115D, "SetSceneIsComplex", "", "" } },
    { "autosave", { 0x115E, "Autosave", "", "" } },
    { "startmasterfileseekdata", { 0x115F, "StartMasterFileSeekData", "", "" } },
    { "dumpmasterfileseekdata", { 0x1160, "DumpMasterFileSeekData", "", "" } },
    { "isactor", { 0x1161, "IsActor", "", "" } },
    { "isessential", { 0x1162, "IsEssential", "", "" } },
    { "preloadmagiceffect", { 0x1163, "PreloadMagicEffect", "", "" } },
    { "showdialogsubtitles", { 0x1164, "ShowDialogSubtitles", "", "" } },
    { "unusedfunction27", { 0x1165, "UnusedFunction27", "", "" } },
    { "isplayermovingintonewspace", { 0x1166, "IsPlayerMovingIntoNewSpace", "", "" } },
    { "unusedfunction28", { 0x1167, "UnusedFunction28", "", "" } },
    { "unusedfunction29", { 0x1168, "UnusedFunction29", "", "" } },
    { "gettimedead", { 0x1169, "GetTimeDead", "", "" } },
    { "getplayerhaslastriddenhorse", { 0x116A, "GetPlayerHasLastRiddenHorse", "", "" } },
    { "getlinkedref", { 0x116B, "GetLinkedRef", "", "" } },
    { "damageobject", { 0x116C, "DamageObject", "do", "" } },
    { "ischild", { 0x116D, "IsChild", "", "" } },
    { "unusedfunction1", { 0x116E, "UnusedFunction1", "", "" } },
    { "getlastplayeraction", { 0x116F, "GetLastPlayerAction", "", "" } },
    { "isplayeractionactive", { 0x1170, "IsPlayerActionActive", "", "" } },
    { "settalkingactivatoractor", { 0x1171, "SetTalkingActivatorActor", "", "" } },
    { "istalkingactivatoractor", { 0x1172, "IsTalkingActivatorActor", "", "" } },
    { "showbartermenu", { 0x1173, "ShowBarterMenu", "sbm", "" } },
    { "isinlist", { 0x1174, "IsInList", "", "" } },
    { "unusedfunction18", { 0x1175, "UnusedFunction18", "", "" } },
    { "addperk", { 0x1176, "AddPerk", "", "" } },
    { "rewardxp", { 0x1177, "RewardXP", "", "" } },
    { "showhackingminigame", { 0x1178, "ShowHackingMiniGame", "shmg", "" } },
    { "showsurgerymenu", { 0x1179, "ShowSurgeryMenu", "ssmg", "" } },
    { "showrepairmenu", { 0x117A, "ShowRepairMenu", "srm", "" } },
    { "functionunused19", { 0x117B, "FunctionUnused19", "unused", "" } },
    { "addnote", { 0x117C, "AddNote", "AN", "" } },
    { "removenote", { 0x117D, "RemoveNote", "RN", "" } },
    { "gethasnote", { 0x117E, "GetHasNote", "GetN", "" } },
    { "addtofaction", { 0x117F, "AddToFaction", "Addfac", "" } },
    { "removefromfaction", { 0x1180, "RemoveFromFaction", "Removefac", "" } },
    { "damageactorvalue", { 0x1181, "DamageActorValue", "DamageAV", "Damage an actor value." } },
    { "restoreactorvalue", { 0x1182, "RestoreActorValue", "RestoreAV", "Restore an actor value." } },
    { "triggerhudshudder", { 0x1183, "TriggerHUDShudder", "hudsh", "Trigger shudder effect on HUD.  Params=Intensity/Duration." } },
    { "setdisposition", { 0x1184, "SetDisposition", "SetDisp", "Sets the dispostion with modifiers" } },
    { "showcomputersinterface", { 0x1185, "ShowComputersInterface", "sci", "" } },
    { "setglobaltimemultiplier", { 0x1186, "SetGlobalTimeMultiplier", "sgtm", "" } },
    { "gethitlocation", { 0x1187, "GetHitLocation", "", "What BGSBodyPart::LIMB_ENUM was hit. -1 = none, 0 = torso, ..." } },
    { "ispc1stperson", { 0x1188, "IsPC1stPerson", "pc1st", "Is the player playing in 1st person mode?" } },
    { "purgecellbuffers", { 0x1189, "PurgeCellBuffers", "pcb", "Forcibly unloads all unattached cells in cell buffers." } },
    { "pushactoraway", { 0x118A, "PushActorAway", "", "" } },
    { "setactorsai", { 0x118B, "SetActorsAI", "", "" } },
    { "clearownership", { 0x118C, "ClearOwnership", "", "" } },
    { "getcauseofdeath", { 0x118D, "GetCauseofDeath", "", "What killed the actor" } },
    { "islimbgone", { 0x118E, "IsLimbGone", "", "Is BGSBodyPart::LIMB_ENUM been dismembered" } },
    { "isweaponinlist", { 0x118F, "IsWeaponInList", "", "Is the current weapon in the form list" } },
    { "playidle", { 0x1190, "PlayIdle", "", "Play this idle on the current actor." } },
    { "applyimagespacemodifier", { 0x1191, "ApplyImageSpaceModifier", "imod", "Adds an imagespace modifier to the active list" } },
    { "removeimagespacemodifier", { 0x1192, "RemoveImageSpaceModifier", "rimod", "Removes an imagespace modifier from the active list" } },
    { "hasfrienddisposition", { 0x1193, "HasFriendDisposition", "", "" } },
    { "functionunused20", { 0x1194, "FunctionUnused20", "", "" } },
    { "frienddispositionboost", { 0x1195, "FriendDispositionBoost", "", "" } },
    { "setcellimagespace", { 0x1196, "SetCellImageSpace", "", "" } },
    { "showchargenmenu", { 0x1197, "ShowChargenMenu", "scgm", "" } },
    { "getvatsvalue", { 0x1198, "GetVATSValue", "", "" } },
    { "iskiller", { 0x1199, "IsKiller", "", "" } },
    { "iskillerobject", { 0x119A, "IsKillerObject", "", "" } },
    { "getfactioncombatreaction", { 0x119B, "GetFactionCombatReaction", "", "" } },
    { "useweapon", { 0x119C, "UseWeapon", "", "" } },
    { "evaluatespellconditions", { 0x119D, "EvaluateSpellConditions", "esc", "" } },
    { "togglemotionblur", { 0x119E, "ToggleMotionBlur", "tmb", "Toggle Motion Blur for the selected reference" } },
    { "exists", { 0x119F, "Exists", "", "" } },
    { "getgroupmembercount", { 0x11A0, "GetGroupMemberCount", "", "" } },
    { "getgrouptargetcount", { 0x11A1, "GetGroupTargetCount", "", "" } },
    { "setobjectivecompleted", { 0x11A2, "SetObjectiveCompleted", "", "Set objective completion status: 0-Off, 1-On" } },
    { "setobjectivedisplayed", { 0x11A3, "SetObjectiveDisplayed", "", "Set objective displayed status: 0-Off, 1-On" } },
    { "getobjectivecompleted", { 0x11A4, "GetObjectiveCompleted", "", "Get objective completion status: 0-Off, 1-On" } },
    { "getobjectivedisplayed", { 0x11A5, "GetObjectiveDisplayed", "", "Get objective displayed status: 0-Off, 1-On" } },
    { "setimagespace", { 0x11A6, "SetImageSpace", "", "" } },
    { "pipboyradio", { 0x11A7, "PipboyRadio", "prad", "Control the Pipboy radio. Enable, Disable, Tune" } },
    { "removeperk", { 0x11A8, "RemovePerk", "", "" } },
    { "disableallactors", { 0x11A9, "DisableAllActors", "DisAA", "" } },
    { "getisformtype", { 0x11AA, "GetIsFormType", "", "" } },
    { "getisvoicetype", { 0x11AB, "GetIsVoiceType", "", "" } },
    { "getplantedexplosive", { 0x11AC, "GetPlantedExplosive", "", "" } },
    { "completeallobjectives", { 0x11AD, "CompleteAllObjectives", "", "Complete all of a quest's objectives" } },
    { "isactortalkingthroughactivator", { 0x11AE, "IsActorTalkingThroughActivator", "", "" } },
    { "gethealthpercentage", { 0x11AF, "GetHealthPercentage", "", "" } },
    { "setaudiomultithreading", { 0x11B0, "SetAudioMultithreading", "SAM", "" } },
    { "getisobjecttype", { 0x11B1, "GetIsObjectType", "", "" } },
    { "showchargenmenuparams", { 0x11B2, "ShowChargenMenuParams", "scgmp", "" } },
    { "getdialogueemotion", { 0x11B3, "GetDialogueEmotion", "", "" } },
    { "getdialogueemotionvalue", { 0x11B4, "GetDialogueEmotionValue", "", "" } },
    { "exitgame", { 0x11B5, "ExitGame", "exit", "" } },
    { "getiscreaturetype", { 0x11B6, "GetIsCreatureType", "", "" } },
    { "setmerchantcontainer", { 0x11B7, "SetMerchantContainer", "", "" } },
    { "removemerchantcontainer", { 0x11B8, "RemoveMerchantContainer", "", "" } },
    { "showwarning", { 0x11B9, "ShowWarning", "", "" } },
    { "entertrigger", { 0x11BA, "EnterTrigger", "", "" } },
    { "markfordelete", { 0x11BB, "MarkForDelete", "", "" } },
    { "additemhealthpercent", { 0x11BC, "AddItemHealthPercent", "", "" } },
    { "placeatmehealthpercent", { 0x11BD, "PlaceAtMeHealthPercent", "", "" } },
    { "getinzone", { 0x11BE, "GetInZone", "", "" } },
    { "disablenavmesh", { 0x11BF, "DisableNavMesh", "", "Disable navmesh by FormID" } },
    { "enablenavmesh", { 0x11C0, "EnableNavMesh", "", "Enable navmesh by FormID" } },
    { "hasperk", { 0x11C1, "HasPerk", "", "" } },
    { "getfactionrelation", { 0x11C2, "GetFactionRelation", "", "" } },
    { "islastidleplayed", { 0x11C3, "IsLastIdlePlayed", "", "" } },
    { "setnpcradio", { 0x11C4, "SetNPCRadio", "snr", "Enable/Disable NPC radio playback: 0-Off, 1-On" } },
    { "setplayerteammate", { 0x11C5, "SetPlayerTeammate", "", "" } },
    { "getplayerteammate", { 0x11C6, "GetPlayerTeammate", "", "" } },
    { "getplayerteammatecount", { 0x11C7, "GetPlayerTeammateCount", "", "" } },
    { "openteammatecontainer", { 0x11C8, "OpenTeammateContainer", "", "" } },
    { "clearfactionplayerenemyflag", { 0x11C9, "ClearFactionPlayerEnemyFlag", "", "" } },
    { "clearactorsfactionsplayerenemyflag", { 0x11CA, "ClearActorsFactionsPlayerEnemyFlag", "", "" } },
    { "getactorcrimeplayerenemy", { 0x11CB, "GetActorCrimePlayerEnemy", "", "" } },
    { "getactorfactionplayerenemy", { 0x11CC, "GetActorFactionPlayerEnemy", "", "" } },
    { "setplayertagskill", { 0x11CD, "SetPlayerTagSkill", "", "" } },
    { "isplayertagskill", { 0x11CE, "IsPlayerTagSkill", "", "" } },
    { "getplayergrabbedref", { 0x11CF, "GetPlayerGrabbedRef", "", "" } },
    { "isplayergrabbedref", { 0x11D0, "IsPlayerGrabbedRef", "", "" } },
    { "placeleveledactoratme", { 0x11D1, "PlaceLeveledActorAtMe", "", "" } },
    { "unusedfunction", { 0x11D2, "UnusedFunction", "", "" } },
    { "showlockpickmenu", { 0x11D3, "ShowLockpickMenu", "slpm", "" } },
    { "getbroadcaststate", { 0x11D4, "GetBroadcastState", "", "" } },
    { "setbroadcaststate", { 0x11D5, "SetBroadcastState", "", "" } },
    { "startradioconversation", { 0x11D6, "StartRadioConversation", "", "" } },
    { "getdestructionstage", { 0x11D7, "GetDestructionStage", "", "" } },
    { "cleardestruction", { 0x11D8, "ClearDestruction", "", "" } },
    { "castimmediateonself", { 0x11D9, "CastImmediateOnSelf", "cios", "" } },
    { "getisalignment", { 0x11DA, "GetIsAlignment", "", "" } },
    { "resetquest", { 0x11DB, "ResetQuest", "", "" } },
    { "setquestdelay", { 0x11DC, "SetQuestDelay", "", "" } },
    { "forceactivequest", { 0x11DD, "ForceActiveQuest", "", "" } },
    { "getthreatratio", { 0x11DE, "GetThreatRatio", "", "" } },
    { "matchfacegeometry", { 0x11DF, "MatchFaceGeometry", "", "" } },
    { "getisuseditemequiptype", { 0x11E0, "GetIsUsedItemEquipType", "", "" } },
    { "getplayername", { 0x11E1, "GetPlayerName", "", "" } },
    { "fireweapon", { 0x11E2, "FireWeapon", "", "" } },
    { "showtutorialmenu", { 0x11E3, "ShowTutorialMenu", "", "" } },
    { "agerace", { 0x11E4, "AgeRace", "", "" } },
    { "matchrace", { 0x11E5, "MatchRace", "", "" } },
    { "setpcyoung", { 0x11E6, "SetPCYoung", "", "" } },
    { "sexchange", { 0x11E7, "SexChange", "", "" } },
    { "showspecialbookmenu", { 0x11E8, "ShowSPECIALBookMenu", "ssbm", "" } },
    { "getconcussed", { 0x11E9, "GetConcussed", "", "" } },
    { "setzonerespawns", { 0x11EA, "SetZoneRespawns", "", "" } },
    { "setvatstarget", { 0x11EB, "SetVATSTarget", "", "" } },
    { "getmapmarkervisible", { 0x11EC, "GetMapMarkerVisible", "", "" } },
    { "resetinventory", { 0x11ED, "ResetInventory", "", "" } },
    { "showspecialbookmenuparams", { 0x11EE, "ShowSPECIALBookMenuParams", "ssbmp", "" } },
    { "getpermanentactorvalue", { 0x11EF, "GetPermanentActorValue", "GetPermAV", "Get an actor value ignoring temporary modifiers. [player.getav luck]" } },
    { "getkillingblowlimb", { 0x11F0, "GetKillingBlowLimb", "", "Which BGSBodyPart::LIMB_ENUM received the killing blow" } },
    { "showbarbermenu", { 0x11F1, "ShowBarberMenu", "", "" } },
    { "showplasticsurgeonmenu", { 0x11F2, "ShowPlasticSurgeonMenu", "", "" } },
    { "triggerlodapocalypse", { 0x11F3, "TriggerLODApocalypse", "", "" } },
    { "getweaponhealthperc", { 0x11F4, "GetWeaponHealthPerc", "", "" } },
    { "setweaponhealthperc", { 0x11F5, "SetWeaponHealthPerc", "", "" } },
    { "modweaponhealthperc", { 0x11F6, "ModWeaponHealthPerc", "", "" } },
    { "getradiationlevel", { 0x11F7, "GetRadiationLevel", "", "" } },
    { "showallmapmarkers", { 0x11F8, "ShowAllMapMarkers", "tmm", "Shows/hidesmap markers (1 shows, 0 hides)(1 travel(default), 0 no travel)(1 all, 0all but hidden(default))." } },
    { "showchargenmenumodvalues", { 0x11F9, "ShowChargenMenuModValues", "scgmod", "" } },
    { "resetai", { 0x11FA, "ResetAI", "", "" } },
    { "setrumble", { 0x11FB, "SetRumble", "", "Creates rumble in the controller (left motor) (right motor) (duration)" } },
    { "setnoactivationsound", { 0x11FC, "SetNoActivationSound", "", "Set the sound to play when activation fails (Sound)" } },
    { "clearnoactivationsound", { 0x11FD, "ClearNoActivationSound", "", "Clear the activation failure sound" } },
    { "getlasthitcritical", { 0x11FE, "GetLastHitCritical", "", "" } },
    { "playmusic", { 0x11FF, "PlayMusic", "", "" } },
    { "setlocationspecificloadscreensonly", { 0x1200, "SetLocationSpecificLoadScreensOnly", "", "" } },
    { "resetpipboymanager", { 0x1201, "ResetPipboyManager", "", "" } },
    { "setpctoddler", { 0x1202, "SetPCToddler", "", "" } },
    { "iscombattarget", { 0x1203, "IsCombatTarget", "", "" } },
    { "rewardkarma", { 0x1204, "RewardKarma", "", "" } },
    { "triggerscreenblood", { 0x1205, "TriggerScreenBlood", "tsb", "Trigger screen blood" } },
    { "getvatsrightareafree", { 0x1206, "GetVATSRightAreaFree", "", "" } },
    { "getvatsleftareafree", { 0x1207, "GetVATSLeftAreaFree", "", "" } },
    { "getvatsbackareafree", { 0x1208, "GetVATSBackAreaFree", "", "" } },
    { "getvatsfrontareafree", { 0x1209, "GetVATSFrontAreaFree", "", "" } },
    { "getislockbroken", { 0x120A, "GetIsLockBroken", "", "" } },
    { "isps3", { 0x120B, "IsPS3", "", "" } },
    { "iswin32", { 0x120C, "IsWin32", "", "" } },
    { "getvatsrighttargetvisible", { 0x120D, "GetVATSRightTargetVisible", "", "" } },
    { "getvatslefttargetvisible", { 0x120E, "GetVATSLeftTargetVisible", "", "" } },
    { "getvatsbacktargetvisible", { 0x120F, "GetVATSBackTargetVisible", "", "" } },
    { "getvatsfronttargetvisible", { 0x1210, "GetVATSFrontTargetVisible", "", "" } },
    { "attachashpile", { 0x1211, "AttachAshPile", "", "" } },
    { "setcriticalstage", { 0x1212, "SetCriticalStage", "", "" } },
    { "isincriticalstage", { 0x1213, "IsInCriticalStage", "", "" } },
    { "removefromallfactions", { 0x1214, "RemoveFromAllFactions", "", "" } },
    { "getxpfornextlevel", { 0x1215, "GetXPForNextLevel", "", "" } },
    { "showlockpickmenudebug", { 0x1216, "ShowLockpickMenuDebug", "slpmd", "" } },
    { "forcesave", { 0x1217, "ForceSave", "", "" } },
    { "setspecialpoints", { 0x1218, "SetSPECIALPoints", "", "" } },
    { "addspecialpoints", { 0x1219, "AddSPECIALPoints", "", "" } },
    { "settagskills", { 0x121A, "SetTagSkills", "", "" } },
    { "addtagskills", { 0x121B, "AddTagSkills", "", "" } },
    { "sin", { 0x121C, "Sin", "", "" } },
    { "cos", { 0x121D, "Cos", "", "" } },
    { "tan", { 0x121E, "Tan", "", "" } },
    { "sqrt", { 0x121F, "Sqrt", "", "" } },
    { "log", { 0x1220, "Log", "", "" } },
    { "abs", { 0x1221, "Abs", "", "" } },
    { "getquestcompleted", { 0x1222, "GetQuestCompleted", "GetQC", "" } },
    { "forceterminalback", { 0x1223, "ForceTerminalBack", "", "" } },
    { "pipboyradiooff", { 0x1224, "PipBoyRadioOff", "", "" } },
    { "autodisplayobjectives", { 0x1225, "AutoDisplayObjectives", "", "" } },
    { "isgoredisabled", { 0x1226, "IsGoreDisabled", "", "" } },
    { "fadesfx", { 0x1227, "FadeSFX", "FSFX", "" } },
    { "setminimaluse", { 0x1228, "SetMinimalUse", "", "" } },
    { "setpccanusepowerarmor", { 0x1229, "SetPCCanUsePowerArmor", "", "" } },
    { "showqueststages", { 0x122A, "ShowQuestStages", "SQS", "" } },
    { "getspellusagenum", { 0x122B, "GetSpellUsageNum", "", "" } },
    { "forceradiostationupdate", { 0x122C, "ForceRadioStationUpdate", "FRSU", "" } },
    { "getactorsinhigh", { 0x122D, "GetActorsInHigh", "", "" } },
    { "hasloaded3d", { 0x122E, "HasLoaded3D", "", "" } },
    { "disableallmines", { 0x122F, "DisableAllMines", "", "" } },
    { "setlastextdooractivated", { 0x1230, "SetLastExtDoorActivated", "", "" } },
    { "killquestupdates", { 0x1231, "KillQuestUpdates", "KQU", "" } },
    { "isimagespaceactive", { 0x1232, "IsImageSpaceActive", "", "" } },
});

std::unordered_map<uint16_t, std::string> FunctionResolver::opcodeFuncs = {
    { 0x1000, "UnusedFunction0" },
    { 0x1001, "GetDistance" },
    { 0x1002, "AddItem" },
    { 0x1003, "SetEssential" },
    { 0x1004, "Rotate" },
    { 0x1005, "GetLocked" },
    { 0x1006, "GetPos" },
    { 0x1007, "SetPos" },
    { 0x1008, "GetAngle" },
    { 0x1009, "SetAngle" },
    { 0x100A, "GetStartingPos" },
    { 0x100B, "GetStartingAngle" },
    { 0x100C, "GetSecondsPassed" },
    { 0x100D, "Activate" },
    { 0x100E, "GetActorValue" },
    { 0x100F, "SetActorValue" },
    { 0x1010, "ModActorValue" },
    { 0x1011, "SetAtStart" },
    { 0x1012, "GetCurrentTime" },
    { 0x1013, "PlayGroup" },
    { 0x1014, "LoopGroup" },
    { 0x1015, "SkipAnim" },
    { 0x1016, "StartCombat" },
    { 0x1017, "StopCombat" },
    { 0x1018, "GetScale" },
    { 0x1019, "IsMoving" },
    { 0x101A, "IsTurning" },
    { 0x101B, "GetLineOfSight" },
    { 0x101C, "AddSpell" },
    { 0x101D, "RemoveSpell" },
    { 0x101E, "Cast" },
    { 0x101F, "GetButtonPressed" },
    { 0x1020, "GetInSameCell" },
    { 0x1021, "Enable" },
    { 0x1022, "Disable" },
    { 0x1023, "GetDisabled" },
    { 0x1024, "MenuMode" },
    { 0x1025, "PlaceAtMe" },
    { 0x1026, "PlaySound" },
    { 0x1027, "GetDisease" },
    { 0x1028, "GetVampire" },
    { 0x1029, "GetClothingValue" },
    { 0x102A, "SameFaction" },
    { 0x102B, "SameRace" },
    { 0x102C, "SameSex" },
    { 0x102D, "GetDetected" },
    { 0x102E, "GetDead" },
    { 0x102F, "GetItemCount" },
    { 0x1030, "GetGold" },
    { 0x1031, "GetSleeping" },
    { 0x1032, "GetTalkedToPC" },
    { 0x1033, "Say" },
    { 0x1034, "SayTo" },
    { 0x1035, "GetScriptVariable" },
    { 0x1036, "StartQuest" },
    { 0x1037, "StopQuest" },
    { 0x1038, "GetQuestRunning" },
    { 0x1039, "SetStage" },
    { 0x103A, "GetStage" },
    { 0x103B, "GetStageDone" },
    { 0x103C, "GetFactionRankDifference" },
    { 0x103D, "GetAlarmed" },
    { 0x103E, "IsRaining" },
    { 0x103F, "GetAttacked" },
    { 0x1040, "GetIsCreature" },
    { 0x1041, "GetLockLevel" },
    { 0x1042, "GetShouldAttack" },
    { 0x1043, "GetInCell" },
    { 0x1044, "GetIsClass" },
    { 0x1045, "GetIsRace" },
    { 0x1046, "GetIsSex" },
    { 0x1047, "GetInFaction" },
    { 0x1048, "GetIsID" },
    { 0x1049, "GetFactionRank" },
    { 0x104A, "GetGlobalValue" },
    { 0x104B, "IsSnowing" },
    { 0x104C, "GetDisposition" },
    { 0x104D, "GetRandomPercent" },
    { 0x104E, "StreamMusic" },
    { 0x104F, "GetQuestVariable" },
    { 0x1050, "GetLevel" },
    { 0x1051, "GetArmorRating" },
    { 0x1052, "RemoveItem" },
    { 0x1053, "ModDisposition" },
    { 0x1054, "GetDeadCount" },
    { 0x1055, "ShowMap" },
    { 0x1056, "StartConversation" },
    { 0x1057, "Drop" },
    { 0x1058, "AddTopic" },
    { 0x1059, "ShowMessage" },
    { 0x105A, "SetAlert" },
    { 0x105B, "GetIsAlerted" },
    { 0x105C, "Look" },
    { 0x105D, "StopLook" },
    { 0x105E, "EvaluatePackage" },
    { 0x105F, "SendAssaultAlarm" },
    { 0x1060, "EnablePlayerControls" },
    { 0x1061, "DisablePlayerControls" },
    { 0x1062, "GetPlayerControlsDisabled" },
    { 0x1063, "GetHeadingAngle" },
    { 0x1064, "PickIdle" },
    { 0x1065, "IsWeaponOut" },
    { 0x1066, "IsTorchOut" },
    { 0x1067, "IsShieldOut" },
    { 0x1068, "CreateDetectionEvent" },
    { 0x1069, "IsActionRef" },
    { 0x106A, "IsFacingUp" },
    { 0x106B, "GetKnockedState" },
    { 0x106C, "GetWeaponAnimType" },
    { 0x106D, "IsWeaponSkillType" },
    { 0x106E, "GetCurrentAIPackage" },
    { 0x106F, "IsWaiting" },
    { 0x1070, "IsIdlePlaying" },
    { 0x1071, "CompleteQuest" },
    { 0x1072, "Lock" },
    { 0x1073, "UnLock" },
    { 0x1074, "GetMinorCrimeCount" },
    { 0x1075, "GetMajorCrimeCount" },
    { 0x1076, "GetActorAggroRadiusViolated" },
    { 0x1077, "GetCrimeKnown" },
    { 0x1078, "SetEnemy" },
    { 0x1079, "SetAlly" },
    { 0x107A, "GetCrime" },
    { 0x107B, "IsGreetingPlayer" },
    { 0x107C, "StartMisterSandMan" },
    { 0x107D, "IsGuard" },
    { 0x107E, "StartCannibal" },
    { 0x107F, "HasBeenEaten" },
    { 0x1080, "GetFatiguePercentage" },
    { 0x1081, "GetPCIsClass" },
    { 0x1082, "GetPCIsRace" },
    { 0x1083, "GetPCIsSex" },
    { 0x1084, "GetPCInFaction" },
    { 0x1085, "SameFactionAsPC" },
    { 0x1086, "SameRaceAsPC" },
    { 0x1087, "SameSexAsPC" },
    { 0x1088, "GetIsReference" },
    { 0x1089, "SetFactionRank" },
    { 0x108A, "ModFactionRank" },
    { 0x108B, "KillActor" },
    { 0x108C, "ResurrectActor" },
    { 0x108D, "IsTalking" },
    { 0x108E, "GetWalkSpeed" },
    { 0x108F, "GetCurrentAIProcedure" },
    { 0x1090, "GetTrespassWarningLevel" },
    { 0x1091, "IsTrespassing" },
    { 0x1092, "IsInMyOwnedCell" },
    { 0x1093, "GetWindSpeed" },
    { 0x1094, "GetCurrentWeatherPercent" },
    { 0x1095, "GetIsCurrentWeather" },
    { 0x1096, "IsContinuingPackagePCNear" },
    { 0x1097, "AddScriptPackage" },
    { 0x1098, "RemoveScriptPackage" },
    { 0x1099, "CanHaveFlames" },
    { 0x109A, "HasFlames" },
    { 0x109B, "AddFlames" },
    { 0x109C, "RemoveFlames" },
    { 0x109D, "GetOpenState" },
    { 0x109E, "MoveToMarker" },
    { 0x109F, "GetSitting" },
    { 0x10A0, "GetFurnitureMarkerID" },
    { 0x10A1, "GetIsCurrentPackage" },
    { 0x10A2, "IsCurrentFurnitureRef" },
    { 0x10A3, "IsCurrentFurnitureObj" },
    { 0x10A4, "SetSize" },
    { 0x10A5, "RemoveMe" },
    { 0x10A6, "DropMe" },
    { 0x10A7, "GetFactionReaction" },
    { 0x10A8, "SetFactionReaction" },
    { 0x10A9, "ModFactionReaction" },
    { 0x10AA, "GetDayOfWeek" },
    { 0x10AB, "IgnoreCrime" },
    { 0x10AC, "GetTalkedToPCParam" },
    { 0x10AD, "RemoveAllItems" },
    { 0x10AE, "WakeUpPC" },
    { 0x10AF, "IsPCSleeping" },
    { 0x10B0, "IsPCAMurderer" },
    { 0x10B1, "SetCombatStyle" },
    { 0x10B2, "PlaySound3D" },
    { 0x10B3, "SelectPlayerSpell" },
    { 0x10B4, "GetDetectionLevel" },
    { 0x10B5, "IsActorDetected" },
    { 0x10B6, "GetEquipped" },
    { 0x10B7, "Wait" },
    { 0x10B8, "StopWaiting" },
    { 0x10B9, "IsSwimming" },
    { 0x10BA, "ScriptEffectElapsedSeconds" },
    { 0x10BB, "SetCellPublicFlag" },
    { 0x10BC, "GetPCSleepHours" },
    { 0x10BD, "SetPCSleepHours" },
    { 0x10BE, "GetAmountSoldStolen" },
    { 0x10BF, "ModAmountSoldStolen" },
    { 0x10C0, "GetIgnoreCrime" },
    { 0x10C1, "GetPCExpelled" },
    { 0x10C2, "SetPCExpelled" },
    { 0x10C3, "GetPCFactionMurder" },
    { 0x10C4, "SetPCFactionMurder" },
    { 0x10C5, "GetPCEnemyofFaction" },
    { 0x10C6, "SetPCEnemyofFaction" },
    { 0x10C7, "GetPCFactionAttack" },
    { 0x10C8, "SetPCFactionAttack" },
    { 0x10C9, "UnusedFunction21" },
    { 0x10CA, "UnusedFunction22" },
    { 0x10CB, "GetDestroyed" },
    { 0x10CC, "SetDestroyed" },
    { 0x10CD, "GetActionRef" },
    { 0x10CE, "GetSelf" },
    { 0x10CF, "GetContainer" },
    { 0x10D0, "GetForceRun" },
    { 0x10D1, "SetForceRun" },
    { 0x10D2, "GetForceSneak" },
    { 0x10D3, "SetForceSneak" },
    { 0x10D4, "AdvancePCSkill" },
    { 0x10D5, "AdvancePCLevel" },
    { 0x10D6, "HasMagicEffect" },
    { 0x10D7, "GetDefaultOpen" },
    { 0x10D8, "SetDefaultOpen" },
    { 0x10D9, "ShowClassMenu" },
    { 0x10DA, "ShowRaceMenu" },
    { 0x10DB, "GetAnimAction" },
    { 0x10DC, "ShowNameMenu" },
    { 0x10DD, "SetOpenState" },
    { 0x10DE, "UnusedFunction26" },
    { 0x10DF, "IsSpellTarget" },
    { 0x10E0, "GetVATSMode" },
    { 0x10E1, "GetPersuasionNumber" },
    { 0x10E2, "GetSandman" },
    { 0x10E3, "GetCannibal" },
    { 0x10E4, "GetIsClassDefault" },
    { 0x10E5, "GetClassDefaultMatch" },
    { 0x10E6, "GetInCellParam" },
    { 0x10E7, "SetInChargen" },
    { 0x10E8, "GetCombatTarget" },
    { 0x10E9, "GetPackageTarget" },
    { 0x10EA, "ShowSpellMaking" },
    { 0x10EB, "GetVatsTargetHeight" },
    { 0x10EC, "SetGhost" },
    { 0x10ED, "GetIsGhost" },
    { 0x10EE, "EquipItem" },
    { 0x10EF, "UnequipItem" },
    { 0x10F0, "SetClass" },
    { 0x10F1, "SetUnconscious" },
    { 0x10F2, "GetUnconscious" },
    { 0x10F3, "SetRestrained" },
    { 0x10F4, "GetRestrained" },
    { 0x10F5, "ForceFlee" },
    { 0x10F6, "GetIsUsedItem" },
    { 0x10F7, "GetIsUsedItemType" },
    { 0x10F8, "UnusedFunction9" },
    { 0x10F9, "UnusedFunction10" },
    { 0x10FA, "UnusedFunction11" },
    { 0x10FB, "UnusedFunction12" },
    { 0x10FC, "UnusedFunction13" },
    { 0x10FD, "UnusedFunction14" },
    { 0x10FE, "GetIsPlayableRace" },
    { 0x10FF, "GetOffersServicesNow" },
    { 0x1100, "GetGameSetting" },
    { 0x1101, "StopCombatAlarmOnActor" },
    { 0x1102, "GetUsedItemLevel" },
    { 0x1103, "GetUsedItemActivate" },
    { 0x1104, "SetWeather" },
    { 0x1105, "ForceTakeCover" },
    { 0x1106, "ModBarterGold" },
    { 0x1107, "SetBarterGold" },
    { 0x1108, "GetBarterGold" },
    { 0x1109, "IsTimePassing" },
    { 0x110A, "IsPleasant" },
    { 0x110B, "IsCloudy" },
    { 0x110C, "TrapUpdate" },
    { 0x110D, "SetQuestObject" },
    { 0x110E, "ForceActorValue" },
    { 0x110F, "ModPCSkill" },
    { 0x1110, "ModPCAttribute" },
    { 0x1111, "EnableFastTravel" },
    { 0x1112, "GetArmorRatingUpperBody" },
    { 0x1113, "GetParentRef" },
    { 0x1114, "PlayBink" },
    { 0x1115, "GetBaseActorValue" },
    { 0x1116, "IsOwner" },
    { 0x1117, "SetOwnership" },
    { 0x1118, "IsCellOwner" },
    { 0x1119, "SetCellOwnership" },
    { 0x111A, "IsHorseStolen" },
    { 0x111B, "SetCellFullName" },
    { 0x111C, "SetActorFullName" },
    { 0x111D, "IsLeftUp" },
    { 0x111E, "IsSneaking" },
    { 0x111F, "IsRunning" },
    { 0x1120, "GetFriendHit" },
    { 0x1121, "IsInCombat" },
    { 0x1122, "SetPackDuration" },
    { 0x1123, "PlayMagicShaderVisuals" },
    { 0x1124, "PlayMagicEffectVisuals" },
    { 0x1125, "StopMagicShaderVisuals" },
    { 0x1126, "StopMagicEffectVisuals" },
    { 0x1127, "ResetInterior" },
    { 0x1128, "IsAnimPlaying" },
    { 0x1129, "SetActorAlpha" },
    { 0x112A, "EnableLinkedPathPoints" },
    { 0x112B, "DisableLinkedPathPoints" },
    { 0x112C, "IsInInterior" },
    { 0x112D, "ForceWeather" },
    { 0x112E, "ToggleActorsAI" },
    { 0x112F, "IsActorsAIOff" },
    { 0x1130, "IsWaterObject" },
    { 0x1131, "UnusedFunction15" },
    { 0x1132, "IsActorUsingATorch" },
    { 0x1133, "SetLevel" },
    { 0x1134, "ResetFallDamageTimer" },
    { 0x1135, "IsXBox" },
    { 0x1136, "GetInWorldspace" },
    { 0x1137, "ModPCMiscStat" },
    { 0x1138, "GetPCMiscStat" },
    { 0x1139, "IsActorEvil" },
    { 0x113A, "IsActorAVictim" },
    { 0x113B, "GetTotalPersuasionNumber" },
    { 0x113C, "SetScale" },
    { 0x113D, "ModScale" },
    { 0x113E, "GetIdleDoneOnce" },
    { 0x113F, "KillAllActors" },
    { 0x1140, "GetNoRumors" },
    { 0x1141, "SetNoRumors" },
    { 0x1142, "Dispel" },
    { 0x1143, "WhichServiceMenu" },
    { 0x1144, "TriggerHitShader" },
    { 0x1145, "FunctionUnused16" },
    { 0x1146, "Reset3DState" },
    { 0x1147, "IsRidingHorse" },
    { 0x1148, "DispelAllSpells" },
    { 0x1149, "UnusedFunction17" },
    { 0x114A, "AddAchievement" },
    { 0x114B, "DuplicateAllItems" },
    { 0x114C, "IsInDangerousWater" },
    { 0x114D, "EssentialDeathReload" },
    { 0x114E, "SetShowQuestItems" },
    { 0x114F, "DuplicateNPCStats" },
    { 0x1150, "ResetHealth" },
    { 0x1151, "SetIgnoreFriendlyHits" },
    { 0x1152, "GetIgnoreFriendlyHits" },
    { 0x1153, "IsPlayersLastRiddenHorse" },
    { 0x1154, "SetActorRefraction" },
    { 0x1155, "SetItemValue" },
    { 0x1156, "SetRigidBodyMass" },
    { 0x1157, "ShowViewerStrings" },
    { 0x1158, "ReleaseWeatherOverride" },
    { 0x1159, "SetAllReachable" },
    { 0x115A, "SetAllVisible" },
    { 0x115B, "SetNoAvoidance" },
    { 0x115C, "SendTrespassAlarm" },
    { 0x115D, "SetSceneIsComplex" },
    { 0x115E, "Autosave" },
    { 0x115F, "StartMasterFileSeekData" },
    { 0x1160, "DumpMasterFileSeekData" },
    { 0x1161, "IsActor" },
    { 0x1162, "IsEssential" },
    { 0x1163, "PreloadMagicEffect" },
    { 0x1164, "ShowDialogSubtitles" },
    { 0x1165, "UnusedFunction27" },
    { 0x1166, "IsPlayerMovingIntoNewSpace" },
    { 0x1167, "UnusedFunction28" },
    { 0x1168, "UnusedFunction29" },
    { 0x1169, "GetTimeDead" },
    { 0x116A, "GetPlayerHasLastRiddenHorse" },
    { 0x116B, "GetLinkedRef" },
    { 0x116C, "DamageObject" },
    { 0x116D, "IsChild" },
    { 0x116E, "UnusedFunction1" },
    { 0x116F, "GetLastPlayerAction" },
    { 0x1170, "IsPlayerActionActive" },
    { 0x1171, "SetTalkingActivatorActor" },
    { 0x1172, "IsTalkingActivatorActor" },
    { 0x1173, "ShowBarterMenu" },
    { 0x1174, "IsInList" },
    { 0x1175, "UnusedFunction18" },
    { 0x1176, "AddPerk" },
    { 0x1177, "RewardXP" },
    { 0x1178, "ShowHackingMiniGame" },
    { 0x1179, "ShowSurgeryMenu" },
    { 0x117A, "ShowRepairMenu" },
    { 0x117B, "FunctionUnused19" },
    { 0x117C, "AddNote" },
    { 0x117D, "RemoveNote" },
    { 0x117E, "GetHasNote" },
    { 0x117F, "AddToFaction" },
    { 0x1180, "RemoveFromFaction" },
    { 0x1181, "DamageActorValue" },
    { 0x1182, "RestoreActorValue" },
    { 0x1183, "TriggerHUDShudder" },
    { 0x1184, "SetDisposition" },
    { 0x1185, "ShowComputersInterface" },
    { 0x1186, "SetGlobalTimeMultiplier" },
    { 0x1187, "GetHitLocation" },
    { 0x1188, "IsPC1stPerson" },
    { 0x1189, "PurgeCellBuffers" },
    { 0x118A, "PushActorAway" },
    { 0x118B, "SetActorsAI" },
    { 0x118C, "ClearOwnership" },
    { 0x118D, "GetCauseofDeath" },
    { 0x118E, "IsLimbGone" },
    { 0x118F, "IsWeaponInList" },
    { 0x1190, "PlayIdle" },
    { 0x1191, "ApplyImageSpaceModifier" },
    { 0x1192, "RemoveImageSpaceModifier" },
    { 0x1193, "HasFriendDisposition" },
    { 0x1194, "FunctionUnused20" },
    { 0x1195, "FriendDispositionBoost" },
    { 0x1196, "SetCellImageSpace" },
    { 0x1197, "ShowChargenMenu" },
    { 0x1198, "GetVATSValue" },
    { 0x1199, "IsKiller" },
    { 0x119A, "IsKillerObject" },
    { 0x119B, "GetFactionCombatReaction" },
    { 0x119C, "UseWeapon" },
    { 0x119D, "EvaluateSpellConditions" },
    { 0x119E, "ToggleMotionBlur" },
    { 0x119F, "Exists" },
    { 0x11A0, "GetGroupMemberCount" },
    { 0x11A1, "GetGroupTargetCount" },
    { 0x11A2, "SetObjectiveCompleted" },
    { 0x11A3, "SetObjectiveDisplayed" },
    { 0x11A4, "GetObjectiveCompleted" },
    { 0x11A5, "GetObjectiveDisplayed" },
    { 0x11A6, "SetImageSpace" },
    { 0x11A7, "PipboyRadio" },
    { 0x11A8, "RemovePerk" },
    { 0x11A9, "DisableAllActors" },
    { 0x11AA, "GetIsFormType" },
    { 0x11AB, "GetIsVoiceType" },
    { 0x11AC, "GetPlantedExplosive" },
    { 0x11AD, "CompleteAllObjectives" },
    { 0x11AE, "IsActorTalkingThroughActivator" },
    { 0x11AF, "GetHealthPercentage" },
    { 0x11B0, "SetAudioMultithreading" },
    { 0x11B1, "GetIsObjectType" },
    { 0x11B2, "ShowChargenMenuParams" },
    { 0x11B3, "GetDialogueEmotion" },
    { 0x11B4, "GetDialogueEmotionValue" },
    { 0x11B5, "ExitGame" },
    { 0x11B6, "GetIsCreatureType" },
    { 0x11B7, "SetMerchantContainer" },
    { 0x11B8, "RemoveMerchantContainer" },
    { 0x11B9, "ShowWarning" },
    { 0x11BA, "EnterTrigger" },
    { 0x11BB, "MarkForDelete" },
    { 0x11BC, "AddItemHealthPercent" },
    { 0x11BD, "PlaceAtMeHealthPercent" },
    { 0x11BE, "GetInZone" },
    { 0x11BF, "DisableNavMesh" },
    { 0x11C0, "EnableNavMesh" },
    { 0x11C1, "HasPerk" },
    { 0x11C2, "GetFactionRelation" },
    { 0x11C3, "IsLastIdlePlayed" },
    { 0x11C4, "SetNPCRadio" },
    { 0x11C5, "SetPlayerTeammate" },
    { 0x11C6, "GetPlayerTeammate" },
    { 0x11C7, "GetPlayerTeammateCount" },
    { 0x11C8, "OpenTeammateContainer" },
    { 0x11C9, "ClearFactionPlayerEnemyFlag" },
    { 0x11CA, "ClearActorsFactionsPlayerEnemyFlag" },
    { 0x11CB, "GetActorCrimePlayerEnemy" },
    { 0x11CC, "GetActorFactionPlayerEnemy" },
    { 0x11CD, "SetPlayerTagSkill" },
    { 0x11CE, "IsPlayerTagSkill" },
    { 0x11CF, "GetPlayerGrabbedRef" },
    { 0x11D0, "IsPlayerGrabbedRef" },
    { 0x11D1, "PlaceLeveledActorAtMe" },
    { 0x11D2, "UnusedFunction" },
    { 0x11D3, "ShowLockpickMenu" },
    { 0x11D4, "GetBroadcastState" },
    { 0x11D5, "SetBroadcastState" },
    { 0x11D6, "StartRadioConversation" },
    { 0x11D7, "GetDestructionStage" },
    { 0x11D8, "ClearDestruction" },
    { 0x11D9, "CastImmediateOnSelf" },
    { 0x11DA, "GetIsAlignment" },
    { 0x11DB, "ResetQuest" },
    { 0x11DC, "SetQuestDelay" },
    { 0x11DD, "ForceActiveQuest" },
    { 0x11DE, "GetThreatRatio" },
    { 0x11DF, "MatchFaceGeometry" },
    { 0x11E0, "GetIsUsedItemEquipType" },
    { 0x11E1, "GetPlayerName" },
    { 0x11E2, "FireWeapon" },
    { 0x11E3, "ShowTutorialMenu" },
    { 0x11E4, "AgeRace" },
    { 0x11E5, "MatchRace" },
    { 0x11E6, "SetPCYoung" },
    { 0x11E7, "SexChange" },
    { 0x11E8, "ShowSPECIALBookMenu" },
    { 0x11E9, "GetConcussed" },
    { 0x11EA, "SetZoneRespawns" },
    { 0x11EB, "SetVATSTarget" },
    { 0x11EC, "GetMapMarkerVisible" },
    { 0x11ED, "ResetInventory" },
    { 0x11EE, "ShowSPECIALBookMenuParams" },
    { 0x11EF, "GetPermanentActorValue" },
    { 0x11F0, "GetKillingBlowLimb" },
    { 0x11F1, "ShowBarberMenu" },
    { 0x11F2, "ShowPlasticSurgeonMenu" },
    { 0x11F3, "TriggerLODApocalypse" },
    { 0x11F4, "GetWeaponHealthPerc" },
    { 0x11F5, "SetWeaponHealthPerc" },
    { 0x11F6, "ModWeaponHealthPerc" },
    { 0x11F7, "GetRadiationLevel" },
    { 0x11F8, "ShowAllMapMarkers" },
    { 0x11F9, "ShowChargenMenuModValues" },
    { 0x11FA, "ResetAI" },
    { 0x11FB, "SetRumble" },
    { 0x11FC, "SetNoActivationSound" },
    { 0x11FD, "ClearNoActivationSound" },
    { 0x11FE, "GetLastHitCritical" },
    { 0x11FF, "PlayMusic" },
    { 0x1200, "SetLocationSpecificLoadScreensOnly" },
    { 0x1201, "ResetPipboyManager" },
    { 0x1202, "SetPCToddler" },
    { 0x1203, "IsCombatTarget" },
    { 0x1204, "RewardKarma" },
    { 0x1205, "TriggerScreenBlood" },
    { 0x1206, "GetVATSRightAreaFree" },
    { 0x1207, "GetVATSLeftAreaFree" },
    { 0x1208, "GetVATSBackAreaFree" },
    { 0x1209, "GetVATSFrontAreaFree" },
    { 0x120A, "GetIsLockBroken" },
    { 0x120B, "IsPS3" },
    { 0x120C, "IsWin32" },
    { 0x120D, "GetVATSRightTargetVisible" },
    { 0x120E, "GetVATSLeftTargetVisible" },
    { 0x120F, "GetVATSBackTargetVisible" },
    { 0x1210, "GetVATSFrontTargetVisible" },
    { 0x1211, "AttachAshPile" },
    { 0x1212, "SetCriticalStage" },
    { 0x1213, "IsInCriticalStage" },
    { 0x1214, "RemoveFromAllFactions" },
    { 0x1215, "GetXPForNextLevel" },
    { 0x1216, "ShowLockpickMenuDebug" },
    { 0x1217, "ForceSave" },
    { 0x1218, "SetSPECIALPoints" },
    { 0x1219, "AddSPECIALPoints" },
    { 0x121A, "SetTagSkills" },
    { 0x121B, "AddTagSkills" },
    { 0x121C, "Sin" },
    { 0x121D, "Cos" },
    { 0x121E, "Tan" },
    { 0x121F, "Sqrt" },
    { 0x1220, "Log" },
    { 0x1221, "Abs" },
    { 0x1222, "GetQuestCompleted" },
    { 0x1223, "ForceTerminalBack" },
    { 0x1224, "PipBoyRadioOff" },
    { 0x1225, "AutoDisplayObjectives" },
    { 0x1226, "IsGoreDisabled" },
    { 0x1227, "FadeSFX" },
    { 0x1228, "SetMinimalUse" },
    { 0x1229, "SetPCCanUsePowerArmor" },
    { 0x122A, "ShowQuestStages" },
    { 0x122B, "GetSpellUsageNum" },
    { 0x122C, "ForceRadioStationUpdate" },
    { 0x122D, "GetActorsInHigh" },
    { 0x122E, "HasLoaded3D" },
    { 0x122F, "DisableAllMines" },
    { 0x1230, "SetLastExtDoorActivated" },
    { 0x1231, "KillQuestUpdates" },
    { 0x1232, "IsImageSpaceActive" },
};

bool FunctionResolver::callFunction(uint16_t opcode)
{
    // TODO: see todo in function.hpp
    if (!FunctionResolver::opcodeFuncs.count(opcode)) {
        return false;
    }

    log_info("%s called", FunctionResolver::opcodeFuncs[opcode].c_str());
    return true;
}

}
